"""initial schema

Revision ID: 9f098866cf98
Revises: e44313142223
Create Date: 2026-03-30 16:56:28.798528

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9f098866cf98'
down_revision = 'e44313142223'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('assignments', schema=None) as batch_op:
        batch_op.drop_column('due_date')

    with op.batch_alter_table('grades', schema=None) as batch_op:
        batch_op.drop_column('comment')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('grades', schema=None) as batch_op:
        batch_op.add_column(sa.Column('comment', sa.VARCHAR(length=200), nullable=True))

    with op.batch_alter_table('assignments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('due_date', sa.DATE(), nullable=True))

    # ### end Alembic commands ###
